/** Error whose message is safe to store; it never contains secret values. */
export class SecretStoreError extends Error {
  constructor(
    readonly code: 'NOT_CONFIGURED' | 'NOT_FOUND' | 'UNAVAILABLE',
    message: string,
  ) {
    super(message);
  }
}

/**
 * Secret manager for customer-provided credentials (ADR-0011). Only a
 * reference returned by `put` is stored in MongoDB; plaintext stays here.
 */
export abstract class SecretStore {
  abstract readonly isConfigured: boolean;
  /** Stores or replaces the secret under `name`; returns its reference. */
  abstract put(name: string, value: string): Promise<string>;
  abstract get(reference: string): Promise<string>;
  abstract delete(reference: string): Promise<void>;
}

/** Used when no secret store is configured; every operation fails. */
export class UnconfiguredSecretStore extends SecretStore {
  readonly isConfigured = false;

  put(): Promise<string> {
    return Promise.reject(this.error());
  }

  get(): Promise<string> {
    return Promise.reject(this.error());
  }

  delete(): Promise<void> {
    return Promise.reject(this.error());
  }

  private error(): SecretStoreError {
    return new SecretStoreError(
      'NOT_CONFIGURED',
      'No secret store is configured for customer credentials',
    );
  }
}

/** Secret names are generated by the control plane, never by clients. */
export function assertSecretName(name: string): void {
  if (!/^[a-z0-9][a-z0-9/_-]{0,200}$/.test(name) || name.includes('..')) {
    throw new SecretStoreError('UNAVAILABLE', 'Invalid secret name');
  }
}
