export interface StoredObject {
  key: string;
  sha256: string;
  sizeBytes: number;
}

/**
 * Transient blob storage for customer-derived content. Keys are generated by
 * the control plane and never derived from client input.
 */
export abstract class ObjectStorage {
  abstract put(content: Buffer): Promise<StoredObject>;
  /** Returns the content after verifying its SHA-256 digest. */
  abstract get(object: StoredObject): Promise<Buffer>;
  /** Deleting a missing object succeeds. */
  abstract delete(key: string): Promise<void>;
}
